apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}-sender
  labels:
    app.kubernetes.io/component: sender
    {{- include "common.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/component: sender
      {{- include "common.selectorLabels" . | nindent 6 }}
  {{- include "common.updateStrategy" . | nindent 2 }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app.kubernetes.io/component: sender
        {{- include "common.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "common.platformContainerRegisterSecret.Name" . }}
      nodeSelector:
        beta.kubernetes.io/os: linux
      {{- include "common.dnsConfig" . | nindent 6 }}
      containers:
        - name: main
          image: "{{ .Values.containerRegisterName }}/sender:{{ default .Chart.AppVersion .Values.image.tag }}"
          imagePullPolicy: Always
          command: ["dotnet"]
          args: ["Sender.dll", "run"]
          ports:
            - containerPort: 80
              protocol: TCP